In [31]:
import pandas as pd
import numpy as np
import pickle
from keras.preprocessing.text import Tokenizer
from keras.models import Sequential
from keras.layers import Activation, Dense, Dropout, Flatten, Conv1D, MaxPooling1D, Input, concatenate
from sklearn.preprocessing import LabelBinarizer
import sklearn.datasets as skds
from keras import optimizers
from pathlib import Path
import jieba
import nltk

In [32]:
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation,GRU
from keras.layers.embeddings import Embedding

In [97]:
# dict='C:/Users/my-pc/Desktop/problem1/newdict.txt'
# with open(dict,'r') as dictfile:
#     dicf=dictfile.readlines()
#     for item in dicf:
#       jieba.del_word(item.replace('\n',''))
#       print(item)

path_train = "C:\\Users\\my-pc\\Desktop\\problem3"
 
files_train = skds.load_files(path_train,load_content=False)
 
label_index = files_train.target
label_names = files_train.target_names
labelled_files = files_train.filenames
 
data_tags = ["filename","category","answers"]
data_list = []
 
# Read and add data from file to a list
i=0
for f in labelled_files:
    data_list.append((f,label_names[label_index[i]],Path(f).read_text()))
    i += 1
 
# We have training data available as dictionary filename, category, data
data = pd.DataFrame.from_records(data_list, columns=data_tags)

In [98]:
data['answers'].shape[0]

1478

In [99]:
for i in range(0,data['answers'].shape[0]):
    data['answers'].iloc[i]=data['answers'].iloc[i].replace(' ','')
    data['answers'].iloc[i]=data['answers'].iloc[i].replace(',','')
    data['answers'].iloc[i]=data['answers'].iloc[i].replace('.','')
    data['answers'].iloc[i]=data['answers'].iloc[i].replace('？','')
    data['answers'].iloc[i]=data['answers'].iloc[i].replace('，','')
    

In [100]:
# ds=[]
# for item in data['answers']:
#     text=str(item).lower()
# #     print(text)
#     chinese="".join(i for i in text if ord(i) >= 256)
#     chlist=[]
#     for i in chinese:
#         chlist.append(i)

#     enlist=[]
#     for i in text:
#         if ord(i) >=256:
#             text=text.replace(i,' ')
#     enlist=list(nltk.word_tokenize(text))
#     listall=enlist+chlist
# #     print(listall)
#     ds.append(listall)
    
    


In [101]:
# stopfile="C:\\Users\\my-pc\\Desktop\\problem1\\stopwords.txt"
# with open(stopfile,'r',encoding='UTF-8') as f:
#    fs=f.readlines()
# for i in range(0,len(fs)):
#     fs[i]=fs[i].replace('\n','')

In [102]:
# for i in range(0,data.shape[0]):
#     ds[i]=[i for i in ds[i] if i not in fs]

In [103]:
num_labels = 6
vocab_size = 2000
batch_size = 100

tokenizer = Tokenizer(num_words=vocab_size,char_level=True)
tokenizer.fit_on_texts(data['answers'])


In [104]:
tokenizer.word_index

{'+': 592,
 '0': 476,
 '1': 305,
 '3': 717,
 '6': 678,
 '7': 414,
 '8': 401,
 'a': 8,
 'b': 376,
 'c': 93,
 'd': 146,
 'e': 64,
 'f': 261,
 'g': 174,
 'h': 173,
 'i': 119,
 'j': 15,
 'k': 195,
 'l': 199,
 'm': 40,
 'n': 102,
 'o': 79,
 'p': 120,
 'q': 621,
 'r': 97,
 's': 90,
 't': 84,
 'u': 159,
 'v': 14,
 'w': 243,
 'x': 407,
 'y': 269,
 'z': 607,
 '、': 18,
 '。': 9,
 '一': 12,
 '七': 471,
 '三': 77,
 '上': 178,
 '下': 133,
 '不': 68,
 '与': 257,
 '专': 481,
 '且': 381,
 '业': 609,
 '东': 177,
 '两': 116,
 '个': 4,
 '中': 51,
 '串': 370,
 '临': 334,
 '为': 21,
 '主': 32,
 '久': 127,
 '么': 82,
 '义': 225,
 '之': 123,
 '乎': 515,
 '九': 559,
 '也': 101,
 '习': 572,
 '书': 564,
 '了': 78,
 '二': 158,
 '于': 131,
 '云': 590,
 '互': 473,
 '五': 74,
 '些': 36,
 '亡': 588,
 '交': 409,
 '产': 341,
 '享': 106,
 '亲': 594,
 '人': 413,
 '什': 100,
 '仅': 612,
 '介': 703,
 '从': 223,
 '他': 259,
 '代': 39,
 '令': 163,
 '以': 65,
 '们': 109,
 '件': 321,
 '价': 746,
 '任': 598,
 '份': 549,
 '伊': 399,
 '优': 451,
 '会': 85,
 '似': 229,
 '但': 226,
 '位': 

In [105]:
data['answers'].iloc[0]

'java这分成两个吧一个栈一个堆是这个吗哎想具体想不太清楚想不太起来。堆的话因为有一个指的是嗯嗯固定分配值的然后就是像一些嗯基础变量所在的地方还有就是非运算对象栈用的地方反正堆和栈啊呀具体分不清楚哪个是哪个了想不起来了。'

In [106]:
test=data['answers'].iloc[0]

In [107]:
train_sequences = tokenizer.texts_to_sequences(test)

In [108]:
train_sequences

[[15],
 [8],
 [14],
 [8],
 [34],
 [16],
 [165],
 [116],
 [4],
 [67],
 [12],
 [4],
 [3],
 [12],
 [4],
 [10],
 [6],
 [34],
 [4],
 [290],
 [419],
 [325],
 [281],
 [251],
 [325],
 [68],
 [230],
 [185],
 [209],
 [325],
 [68],
 [230],
 [338],
 [75],
 [9],
 [10],
 [2],
 [47],
 [271],
 [21],
 [13],
 [12],
 [4],
 [112],
 [2],
 [6],
 [23],
 [23],
 [613],
 [183],
 [16],
 [205],
 [244],
 [2],
 [30],
 [26],
 [24],
 [6],
 [115],
 [12],
 [36],
 [23],
 [135],
 [291],
 [63],
 [44],
 [105],
 [57],
 [2],
 [28],
 [5],
 [20],
 [13],
 [24],
 [6],
 [187],
 [107],
 [180],
 [48],
 [58],
 [3],
 [53],
 [2],
 [28],
 [5],
 [448],
 [326],
 [10],
 [37],
 [3],
 [49],
 [186],
 [281],
 [251],
 [16],
 [68],
 [185],
 [209],
 [145],
 [4],
 [6],
 [145],
 [4],
 [78],
 [325],
 [68],
 [338],
 [75],
 [78],
 [9]]

In [109]:
train_sequences = tokenizer.texts_to_sequences(data['answers'])

In [110]:
datas = pad_sequences(train_sequences, maxlen=200)

In [111]:
# num_labels = 6
# vocab_size = 5000
# batch_size = 100

# tokenizer = Tokenizer(num_words=vocab_size,filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~')
# tokenizer.fit_on_texts(train_posts)

# x_train = tokenizer.texts_to_matrix(train_posts, mode='count')
# x_test = tokenizer.texts_to_matrix(test_posts, mode='count')
# encoder = LabelBinarizer()
# encoder.fit(train_tags)
# y_train = encoder.transform(train_tags)
# y_test = encoder.transform(test_tags)

In [112]:
data['category']

0       2
1       3
2       2
3       3
4       4
5       2
6       2
7       2
8       3
9       4
10      2
11      4
12      4
13      4
14      2
15      2
16      1
17      3
18      2
19      2
20      2
21      4
22      4
23      2
24      2
25      2
26      4
27      4
28      2
29      1
       ..
1448    5
1449    4
1450    1
1451    3
1452    2
1453    3
1454    3
1455    1
1456    3
1457    1
1458    3
1459    2
1460    3
1461    1
1462    1
1463    2
1464    2
1465    2
1466    4
1467    2
1468    4
1469    2
1470    2
1471    3
1472    4
1473    3
1474    3
1475    4
1476    2
1477    2
Name: category, Length: 1478, dtype: object

In [113]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(datas, data['category'], test_size=0.2)

In [114]:
y_train

189     1
1176    3
506     3
1244    2
840     2
566     1
177     2
1177    3
413     4
584     2
766     2
561     2
200     2
265     4
1255    3
383     3
1128    2
256     1
26      4
617     4
1085    2
916     1
147     4
1092    1
1186    3
518     4
109     2
397     2
1431    3
960     3
       ..
512     2
280     1
658     3
1212    5
1453    3
52      4
1306    3
75      1
606     2
991     2
360     2
854     1
1075    2
364     2
753     3
137     4
1185    4
1086    4
513     3
629     4
1097    5
22      4
1151    2
714     2
1374    1
898     4
1322    2
1325    2
1283    1
102     2
Name: category, Length: 1182, dtype: object

In [115]:
# train_sequences = tokenizer.texts_to_sequences(str(x_train.iloc[0]))
# x_test = tokenizer.texts_to_matrix(x_test, mode='count')
encoder = LabelBinarizer()
print(encoder.fit(data['category']))

y_train = encoder.transform(y_train)
y_test = encoder.transform(y_test)
y_train

LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)


array([[1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       ...,
       [0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0]])

In [116]:
# a = np.zeros(x_train.shape[0])
# for i in range(0,x_train.shape[0]):
#     a[i]=len(data['answers'].iloc[i])

In [117]:
# x_train=np.column_stack((x_train,a))

In [118]:
# b=np.zeros(x_test.shape[0])
# for i in range(0,x_test.shape[0]):
#     b[i]=len(data['answers'].iloc[i+x_train.shape[0]])
# x_test=np.column_stack((x_test,b))

In [22]:
# model = Sequential()
# model.add(Dense(256, input_shape=(vocab_size,)))
# model.add(Activation('relu'))
# model.add(Dropout(0.5))
# model.add(Dense(256))
# model.add(Activation('relu'))
# model.add(Dropout(0.5))
# model.add(Dense(256))
# model.add(Activation('relu'))
# model.add(Dropout(0.5))
# model.add(Dense(num_labels))
# model.add(Activation('softmax'))
# model.summary()
# sgd = optimizers.SGD(lr=0.01, clipvalue=0.5)
# model.compile(loss='categorical_crossentropy',
#               optimizer='adam',
#               metrics=['accuracy'])
 
# history = model.fit(x_train, y_train,
#                     batch_size=batch_size,
#                     epochs=120,
#                     verbose=1,
#                     validation_split=0.1)

#  DNN模型
model = Sequential()
model.add(Embedding(5000, 50, input_length=200))
model.add(Dropout(0.2))
model.add(Conv1D(100, 5, activation='relu'))
model.add(MaxPooling1D(pool_size=4))
model.add(LSTM(100, dropout=0.5, recurrent_dropout=0.2))
model.add(Dense(num_labels))
model.add(Activation('softmax'))
# model.add(Dense(1))
# model.add(Activation('sigmoid'))
# model.add(Dense(1, activation='sigmoid'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, validation_split=0.1, epochs=30)

# rnn lstm分类

Train on 1087 samples, validate on 121 samples
Epoch 1/30
1087/1087 [==============================] - 31s 29ms/step - loss: 1.3117 - acc: 0.4002 - val_loss: 1.1159 - val_acc: 0.5455
Epoch 2/30
1087/1087 [==============================] - 4s 3ms/step - loss: 0.9804 - acc: 0.5823 - val_loss: 0.8651 - val_acc: 0.6529
Epoch 3/30
1087/1087 [==============================] - 4s 3ms/step - loss: 0.8779 - acc: 0.6247 - val_loss: 0.7702 - val_acc: 0.6860
Epoch 4/30
1087/1087 [==============================] - 4s 4ms/step - loss: 0.8377 - acc: 0.6477 - val_loss: 0.7511 - val_acc: 0.7025
Epoch 5/30
1087/1087 [==============================] - 4s 4ms/step - loss: 0.7908 - acc: 0.6624 - val_loss: 0.7071 - val_acc: 0.6860
Epoch 6/30
1087/1087 [==============================] - 4s 4ms/step - loss: 0.7426 - acc: 0.6983 - val_loss: 0.6928 - val_acc: 0.7273
Epoch 7/30
1087/1087 [==============================] - 4s 4ms/step - loss: 0.6955 - acc: 0.7019 - val_loss: 0.6975 - val_acc: 0.7273
Epoch 8/30
10

In [119]:
def text_cnn(maxlen=200, max_features=2000, embed_size=32):
    # Inputs
    seq = Input(shape=[maxlen], name='x_seq')

    # Embeddings layers
    emb_comment = Embedding(max_features, embed_size)(seq)

    # conv layers
    convs = []
    filter_sizes = [2,3, 4, 5]
    for fsz in filter_sizes:
        l_conv = Conv1D(filters=100, kernel_size=fsz, activation='relu')(emb_comment)

        l_pool = MaxPooling1D(maxlen - fsz + 1)(l_conv)
        l_pool = Flatten()(l_pool)
        
#         inner = Reshape(target_shape=(( 100,1)), name='reshape')(l_pool)
#         gru=GRU(64,dropout=0.5,recurrent_dropout=0.5,return_sequences=True)(inner)

        convs.append(l_pool)
    merge = concatenate(convs, axis=1)
    #merge = Reshape(target_shape=((512)), name='reshape')(merge)
    
    out = Dropout(0.5)(merge)
    output = Dense(32, activation='relu')(out)

    output = Dense(units=6, activation='softmax')(output)

    model = Model([seq], output)
    #     adam = optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
    model.compile(loss="binary_crossentropy", optimizer="adam", metrics=['accuracy'])
    return model

In [120]:
from keras.models import Model
from keras.layers import Reshape
model = text_cnn()
print(model.output_shape)
batch_size = 128
epochs = 50
model.fit(x_train, y_train,
          validation_split=0.1,
          batch_size=batch_size,
          epochs=epochs,
          shuffle=True)

(None, 6)
Train on 1063 samples, validate on 119 samples
Epoch 1/50
1063/1063 [==============================] - 3s 3ms/step - loss: 0.4329 - acc: 0.8333 - val_loss: 0.4137 - val_acc: 0.8333
Epoch 2/50
1063/1063 [==============================] - 0s 420us/step - loss: 0.3972 - acc: 0.8333 - val_loss: 0.3877 - val_acc: 0.8333
Epoch 3/50
1063/1063 [==============================] - 0s 415us/step - loss: 0.3719 - acc: 0.8333 - val_loss: 0.3495 - val_acc: 0.8333
Epoch 4/50
1063/1063 [==============================] - 0s 433us/step - loss: 0.3435 - acc: 0.8362 - val_loss: 0.3089 - val_acc: 0.8557
Epoch 5/50
1063/1063 [==============================] - 0s 435us/step - loss: 0.3111 - acc: 0.8628 - val_loss: 0.2700 - val_acc: 0.8964
Epoch 6/50
1063/1063 [==============================] - 0s 429us/step - loss: 0.2791 - acc: 0.8719 - val_loss: 0.2429 - val_acc: 0.9034
Epoch 7/50
1063/1063 [==============================] - 0s 421us/step - loss: 0.2564 - acc: 0.8866 - val_loss: 0.2207 - val_acc: 

In [121]:
score = model.evaluate(x_test, y_test, batch_size=batch_size, verbose=1)
print('Test accuracy:', score[1])

296/296 [==============================] - 1s 2ms/step
Test accuracy: 0.8941441629384015


In [122]:
from sklearn.metrics import confusion_matrix
import pandas as pd
import tensorflow as tf

In [124]:
predict_test = model.predict(x_train)
print(predict_test)
predict = np.argmax(predict_test,axis=1)
#axis = 1是取行的最大值的索引，0是列的最大值的索引
y_train = encoder.inverse_transform(y_train)
print(y_train)
prenumbers=list(map(int, predict))
uanumbers=list(map(int, y_train))
print(confusion_matrix(uanumbers,prenumbers))


[[9.9886900e-01 1.0891416e-03 2.9914983e-05 1.1105255e-05 7.6881201e-07
  1.1812241e-07]
 [2.7965560e-05 2.6663342e-01 7.3059374e-01 2.7014881e-03 4.3167725e-05
  1.6569567e-07]
 [3.5901085e-04 9.7019508e-02 8.3780497e-01 6.3844338e-02 9.7183086e-04
  3.6687405e-07]
 ...
 [4.0993422e-05 3.4091154e-01 6.5631878e-01 2.6072518e-03 1.2114404e-04
  2.4991473e-07]
 [9.6909863e-01 2.9991871e-02 7.8648946e-04 1.0325833e-04 1.9300442e-05
  4.3760619e-07]
 [9.8721328e-05 9.5956695e-01 4.0270951e-02 5.8449579e-05 4.7766366e-06
  1.1101998e-07]]
['1' '3' '3' ... '2' '1' '2']
[[  0   0   0   0   0   0]
 [167   7   0   0   0   0]
 [  2 397  11   2   0   0]
 [  0  21 207  53   0   0]
 [  0   0  10 266   0   0]
 [  0   0   0   8  31   0]]


In [49]:
from xgboost import XGBClassifier
import xgboost as xgb
from sklearn import preprocessing
import pandas as pd 
import numpy as np
import sklearn
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold

from sklearn.metrics import log_loss

In [50]:
param = {}
param['objective'] = 'multi:softmax'
# scale weight of positive examples
param['eta'] = 0.01
param['max_depth'] = 10

param['n_estimators']=5000
param['silent'] = 1
param['nthread'] = 4
param['num_class'] = 7


In [51]:

le = preprocessing.LabelEncoder()
y_train=encoder.inverse_transform(y_train)
y_test=encoder.inverse_transform(y_test)

In [52]:
xg_train = xgb.DMatrix(x_train, label=y_train)
xg_test = xgb.DMatrix( x_test, label=y_test)

In [53]:
watchlist = [ (xg_train,'train'), (xg_test, 'test') ]
num_round = 120
bst = xgb.train(param, xg_train, num_round, watchlist );

[0]	train-merror:0.139073	test-merror:0.435644
[1]	train-merror:0.123344	test-merror:0.432343
[2]	train-merror:0.111755	test-merror:0.429043
[3]	train-merror:0.106788	test-merror:0.425743
[4]	train-merror:0.114238	test-merror:0.422442
[5]	train-merror:0.110099	test-merror:0.409241
[6]	train-merror:0.110927	test-merror:0.415842
[7]	train-merror:0.104305	test-merror:0.409241
[8]	train-merror:0.103477	test-merror:0.405941
[9]	train-merror:0.100993	test-merror:0.39604
[10]	train-merror:0.100993	test-merror:0.40264
[11]	train-merror:0.095199	test-merror:0.392739
[12]	train-merror:0.095199	test-merror:0.392739
[13]	train-merror:0.096854	test-merror:0.389439
[14]	train-merror:0.096854	test-merror:0.39604
[15]	train-merror:0.096854	test-merror:0.392739
[16]	train-merror:0.095199	test-merror:0.379538
[17]	train-merror:0.091887	test-merror:0.382838
[18]	train-merror:0.090232	test-merror:0.382838
[19]	train-merror:0.088576	test-merror:0.389439
[20]	train-merror:0.088576	test-merror:0.389439
[21]	

In [54]:
# sklearn.metrics.confusion_matrix(
#     y_test,   # array, Gound true (correct) target values
#     test_pred,  # array, Estimated targets as returned by a classifier
#     labels=None,  # array, List of labels to index the matrix.
#     sample_weight=None  # array-like of shape = [n_samples], Optional sample weights
# )

In [71]:
ctrain=xgb.DMatrix(x_test)
predict_test = bst.predict(ctrain)
print(predict_test)
uanumbers=list(map(int, predict_test))
umbers = list(map(int, y_test))
print(predict_test[4])
print(confusion_matrix(uanumbers,umbers))


[4. 3. 4. 1. 4. 3. 3. 2. 3. 4. 4. 3. 4. 3. 4. 4. 4. 2. 4. 3. 4. 3. 3. 4.
 4. 4. 3. 1. 4. 3. 2. 3. 1. 2. 3. 1. 4. 2. 5. 3. 2. 3. 4. 3. 2. 3. 4. 4.
 3. 3. 3. 3. 3. 4. 3. 3. 4. 4. 3. 1. 3. 3. 4. 3. 4. 4. 4. 4. 3. 4. 3. 4.
 4. 3. 4. 4. 4. 4. 3. 3. 3. 3. 3. 3. 4. 3. 2. 3. 3. 3. 3. 3. 3. 3. 4. 5.
 4. 4. 4. 3. 4. 4. 3. 2. 4. 2. 4. 5. 3. 3. 3. 3. 4. 3. 3. 4. 2. 3. 5. 3.
 3. 4. 4. 3. 1. 3. 3. 2. 3. 3. 4. 3. 3. 1. 3. 4. 3. 4. 3. 3. 4. 3. 4. 4.
 4. 3. 1. 4. 3. 3. 3. 3. 2. 4. 3. 3. 4. 2. 4. 4. 4. 2. 3. 3. 3. 3. 1. 4.
 4. 3. 4. 3. 4. 4. 4. 1. 4. 3. 4. 3. 2. 4. 4. 4. 4. 4. 4. 4. 4. 1. 2. 3.
 4. 3. 3. 3. 3. 3. 4. 3. 3. 1. 2. 2. 4. 3. 5. 3. 3. 4. 4. 3. 4. 4. 3. 4.
 2. 3. 4. 4. 4. 4. 3. 4. 3. 3. 2. 4. 3. 4. 3. 1. 2. 3. 4. 1. 2. 5. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 4. 3. 4. 3. 3. 3. 3. 4. 4. 4. 3. 4. 3.
 4. 3. 3. 4. 3. 2. 3. 3. 4. 3. 2. 3. 2. 2. 1. 3. 4. 3. 3. 4. 4. 4. 2. 3.
 3. 1. 1. 4. 3. 3. 4. 4. 3. 3. 4. 3. 4. 4. 3.]
4.0
[[14  3  0  0  0]
 [ 4 20  4  0  0]
 [ 1 22 87 29  2]
 [ 0  3 27 72  9]
 